#!/bin/bash

echo ":menu-ubuntu"

dists=$(curl -l ftp://mirrors.kernel.org/ubuntu/dists/ 2>/dev/null \
	| grep -v backports \
	| grep -v proposed \
	| grep -v security \
	| grep -v updates \
	)

for dist in $dists
do
	# Generate the menu

	for arch in i386 amd64
	do
		echo "item ubuntu-$dist-$arch Install Ubuntu $dist $arch"
	done
done

echo "item"
echo "item --key x back <=== Back to main menu..."
echo "choose selected && goto \${selected} || goto start"
echo ""

for dist in $dists
do
	# Generate the startup items
	for arch in i386 amd64
	do
		echo ":ubuntu-$dist-$arch"
		echo "sanboot --no-describe ftp://mirrors.kernel.org/ubuntu/dists/$dist/main/installer-$arch/current/images/netboot/mini.iso || goto failed"
		echo ""
	done
done
